# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b63b3448f52194a45689252fb5bce03f121707f6689f0b3c98e88c8e1681290352aa691908fb3366442d65bd50815aca80ebbb552aecc58ba41c9f0a3549fa

test:
  secret_key_base: d5626c1e0a72d95ae6fbfe4daed0dc2a04c618d83ea38c1f76579330e10e36e025cb96d3af6f81b9f19bcdaac38136b56e05760c8ba9aae5e12e693934faaa64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
